version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: ibrahim
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: aeroponic
    networks:
      - ibrahimgb
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: ibrahim
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: aeroponic
    networks:
      - ibrahimgb
  test-dev-db:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123test
      POSTGRES_DB: nest
    networks:
      - ibrahimgb
networks:
  ibrahimgb: