-- AlterTable
ALTER TABLE "AeroponicTower" ADD COLUMN     "dayStarted" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "daysToHarvest" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "image" TEXT;
